### PR TITLE
[RYSK-156] Only Issue option if not already present in OptionRegistry

### PR DESCRIPTION
**Pull request by devey**
On the buy flow, there is no need to send an`Issue` operation if the series has already been added to the `OptionRegistry`.

### CODE REVIEW

**Review by MeanBoyCousin — COMMENTED** [review]
What's the implied downside to calling `issue` even if it already exists?

**Comment by devey** [comment]
@MeanBoyCousin just the smart contract going through unnecessary logic, but for the FE it doesn't affect the outcome having it or not

**Comment by MeanBoyCousin** [comment]
> @MeanBoyCousin just the smart contract going through unnecessary logic, but for the FE it doesn't affect the outcome having it or not

In that case, if the only way to do this is through a network request I would prefer to avoid it.

**Comment by MeanBoyCousin** [comment]
Closing as the network overhead outweighs the benefits.

**Pull request closed without merging**
